const ACTIONS = {
    //USERS
    LOGIN: "LOGIN",
    GET_TOKEN: "GET_TOKEN",
    GET_USER: "GET_USER",
    GET_ALL_USERS: "GET_ALL_USERS",

    //ORGANIZATION
    CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
    GET_ORGANIZATION: "GET_ORGANIZATION",
    GET_ORGANIZATION_ALL_EVENT: "GET_ORGANIZATION_ALL_EVENT",

    //EVENTS
    GET_EVENTS_BY_USERID_LOADING: "GET_EVENTS_BY_USERID_LOADING",
    GET_EVENTS_BY_USERID_SUCCESS: "GET_EVENTS_BY_USERID_SUCCESS",
    GET_EVENTS_BY_USERID_FAIL: "GET_EVENTS_BY_USERID_FAIL",

    GET_SINGLE_EVENT_LOADING: "GET_SINGLE_EVENT_LOADING",
    GET_SINGLE_EVENT_SUCCESS: "GET_SINGLE_EVENT_SUCCESS",
    GET_SINGLE_EVENT_FAIL: "GET_SINGLE_EVENT_FAIL",

    GET_EVENTS_LOADING: "GET_EVENTS_LOADING",
    GET_EVENTS_SUCCESS: "GET_EVENTS_SUCCESS",
    GET_EVENTS_FAIL: "GET_EVENTS_FAIL",

    ADD_EVENT_LOADING: "ADD_EVENT_LOADING",
    ADD_EVENT_SUCCESS: "ADD_EVENT_SUCCESS",
    ADD_EVENT_FAIL: "ADD_EVENT_FAIL",

    DELETE_EVENT_LOADING: "DELETE_EVENT_LOADING",
    DELETE_EVENT_SUCCESS: "DELETE_MESSAGE_SUCCESS",
    DELETE_EVENT_FAIL: "DELETE_EVENT_FAIL",

    EDIT_EVENT_LOADING: "EDIT_EVENT_LOADING",
    EDIT_EVENT_SUCCESS: "EDIT_EVENT_SUCCESS",
    EDIT_EVENT_FAIL: "EDIT_EVENT_FAIL",
};

export default ACTIONS;
