const ACTIONS = {
    //USERS
    LOGIN: "LOGIN",
    GET_TOKEN: "GET_TOKEN",
    GET_USER: "GET_USER",
    GET_ALL_USERS: "GET_ALL_USERS",

    //ORGANIZATION
    CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
    GET_ORGANIZATION: "GET_ORGANIZATION",
    GET_ORGANIZATION_ALL_EVENT: "GET_ORGANIZATION_ALL_EVENT",

    //EVENTS`
    GET_ALL_USER_EVENTS: "GET_ALL_USER_EVENTS",
    SET_SINGLE_EVENT: "SET_SINGLE_EVENT",
    GET_ALL_EVENTS: "GET_ALL_EVENTS",
    GET_SINGLE_EVENT: "GET_SINGLE_EVENT",

    //BOOTH
    SET_SINGLE_BOOTH: "SET_SINGLE_BOOTH",
    GET_ALL_EVENT_BOOTHS: "GET_ALL_EVENT_BOOTHS",
    GET_SINGLE_BOOTH: "GET_SINGLE_BOOTH",
    GET_IS_EVENT_HOST: "GET_IS_EVENT_HOST",
    ADD_BOOTH: "ADD_BOOTH",

    // GET_ALL_EVENTS: "GET_ALL_EVENTS",
    // //ADDITIONAL
    // GET_ALL_HOSTING_EVENTS: "GET_ALL_HOSTING_EVENTS",
    // GET_ALL_PASS_EVENTS: "GET_ALL_PASS_EVENTS",
};

export default ACTIONS;
