// ORGANIZATION
export const GET_ORGANIZATION_LOADING = "GET_ORGANIZATION_LOADING";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAIL = "GET_ORGANIZATION_FAIL";
